version: "3"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/phpspec-tdd-affordability-exercise
    working_dir: /var/www/phpspec-tdd-affordability-exercise
    environment:
      APPLICATION_ENV: docker
